import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <Link href={'/'}><h1>SSE Entregas</h1></Link>
          <nav>
            <Link href={"/encomendas"}>ENCOMENDAS</Link>
            <Link href={"/entregadores"}>ENTREGADORES</Link>
            <Link href={"/rastreamento-status"}>RASTREAMENTOS</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
